- name: Create index.php
  copy: src=index.php dest=/var/www/ owner=vagrant mode=0644
  tags:
    - demo

- name: Create php.php
  copy: src=php.php dest=/var/www/ owner=vagrant mode=0644
  tags:
    - demo

- name: Copy views
  copy: src=views dest=/var/www/ owner=vagrant mode=0644
  tags:
    - demo

- name: Copy assets
  copy: src=assets dest=/var/www/ owner=vagrant mode=0644
  tags:
    - demo