language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

# run build against PHP 5.6 and hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly

install:
  - composer self-update && composer --version
  - composer install --prefer-dist
  - composer require satooshi/php-coveralls:*@dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v